# Generated by Django 5.2.18 on 2026-10-08 17:26

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9999)], verbose_name='Número')),
                ('tipo', models.CharField(choices=[('individual', 'Individual'), ('doble', 'Doble'), ('suite', 'Suite'), ('familiar', 'Familiar')], max_length=20, verbose_name='Tipo')),
                ('capacidad', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Capacidad')),
                ('precio_noche', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio por noche CLP')),
                ('piso', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Piso')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('ocupada', 'Ocupada'), ('mantenimiento', 'En mantenimiento')], default='disponible', max_length=20, verbose_name='Estado')),
                ('descripcion', models.TextField(blank=True, max_length=500, verbose_name='Descripción')),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('actualizada', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'habitaciones',
                'ordering': ['numero'],
                'constraints': [models.CheckConstraint(check=models.Q(('numero__gte', 1), ('numero__lte', 9999)), name='numero_valido'), models.CheckConstraint(check=models.Q(('capacidad__gte', 1), ('capacidad__lte', 10)), name='capacidad_valida'), models.CheckConstraint(check=models.Q(('precio_noche__gt', 0)), name='precio_positivo'), models.CheckConstraint(check=models.Q(('piso__gte', 0), ('piso__lte', 100)), name='piso_valido'), models.CheckConstraint(check=models.Q(('tipo__in', ['individual', 'doble', 'suite', 'familiar'])), name='tipo_valido'), models.CheckConstraint(check=models.Q(('estado__in', ['disponible', 'ocupada', 'mantenimiento'])), name='estado_valido')],
            },
        ),
    ]
